FROM ubuntu

RUN apt update && apt install git -y && apt install genisoimage -y && apt install bash -y

WORKDIR /home/app/

RUN git clone https://github.com/VladimirNikel/SP_laba1.git \
	&& cd SP_laba1/ \
	&& chmod ugo+x 2.sh
